### ISSUE TITLE
registry branches have drifted from main; provider payloads fail their own install gates

### ISSUE THREAD

**Issue by glifocat** [nanocoai/nanoclaw#3155]
## What happens

Running `/add-codex` on `main` at 0b034342 fails at the skill's own build step. I applied the skill mechanically (payload copy, barrel imports, CLI manifest entry) on that revision with the payload from `providers` at f2b75837, then ran the skill's step-4 typecheck:

```
container/agent-runner/src/providers/codex.ts(395,17): error TS2322: Type '"file"' is not assignable to type '"error" | "init" | "result" | "progress" | "activity"'.
```

The registration and behavior tests all pass in the same composition (42/42 bun, 18/18 vitest). The guards are green while the build gate is red, so the tests cannot catch this class of drift.

The `providers` branch also fails `tsc` against itself: its codex payload (updated in #3013) imports `ProviderExchange` and reads `options.model` / `options.effort`, which only exist on `main` since 2026-07-15 (76d941b2, 91695717) and were never forward-merged into the branch.

## Why it happens

Two drifts stacked:

1. Neither registry branch has merged `main` since 2026-04-28. A merge simulation at 0b034342 shows 37 conflicting paths on `channels` and 23 on `providers`.
2. The codex payload's core half never landed on `main`. The `{ type: 'file' }` provider event (codex image delivery, added 904871aa) needs a `ProviderEvent` union member and a poll-loop handler. Both exist on the codex development line (verified on a live install at 8f9c596e, branch `feat/codex-reconnect`: union member at `types.ts:140`, handler at `poll-loop.ts:561`, clean tsc) but on none of the refs I checked: `main` at 0b034342, `providers` at f2b75837, and the pushed `feat/codex-reconnect` on `glifocat/nanoclaw` at b69c3603. The pieces live only in local commits on the machine running that install. Until they land, the feature is dead code everywhere except that dev line.

## How to see it

From any clone of this repo (the SHAs pin the tested revisions; the failure should disappear once the fix lands):

```bash
git fetch origin main providers
git worktree add /tmp/drift-test 0b034342
cd /tmp/drift-test
# apply .claude/skills/add-codex/SKILL.md install steps 1 to 3 at the tested payload revision:
#   step 1: for each of the 18 listed payload files: git show f2b75837:<path> > <path>
#   step 2: append the three barrel imports
#   step 3: add the CLI manifest entry to container/cli-tools.json
pnpm install
cd container/agent-runner && bun install && cd ../..
pnpm exec tsc -p container/agent-runner/tsconfig.json --noEmit
```

The last command is the skill's own step-4 gate and fails with the error above.

## Second occurrence: the same class hit `/add-opencode` (added 2026-07-30)

The opencode payload on [#3122](https://github.com/nanocoai/nanoclaw/pull/3122) walked into the identical trap from the other direction: its attachment fixes edited `container/agent-runner/src/providers/types.ts`, `formatter.ts`, and `poll-loop.ts` on the `providers` branch. None of those files is in `/add-opencode`'s copy list, and registry branches never merge back, so on `main` at 4e83a0a the copied provider file failed the skill's own typecheck gate (TS2305 `PromptAttachment`, TS2339 `attachments`) and, past that, the feature was dead code because `main`'s poll-loop passes no attachments.

The fix demonstrated there is the same sequence this issue prescribes: the trunk half became a standalone `main` PR (#3156), and the provider file was reworked to compile on both trees by declaring the shape locally instead of importing it, the way the codex payload should eventually treat the `file` event. Two providers hitting the same wall independently is the pattern this issue exists to name: provider work on a registry branch cannot carry trunk-side halves, and nothing in the skill gates catches it before a user does.

## Suggested fix (order matters)

1. Land the core half on `main`: add the `file` member to `ProviderEvent` and the poll-loop handling. The reference implementation is in unpushed local commits on the `feat/codex-reconnect` install, so this needs that work pushed first, or a fresh extraction.
2. Forward-merge `main` into `providers`. This also picks up `ProviderExchange` and `model`/`effort`, and auto-removes the `bump-version.yml` / `update-tokens.yml` workflows that `main` deleted.
3. Forward-merge `main` into `channels` (the larger one; plan it as its own reviewed effort per docs/BRANCH-FORK-MAINTENANCE.md).
4. Re-verify `/add-codex` and `/add-opencode` on a clean `main` worktree using each skill's own validate steps.

Forward-merging `main` into `providers` supplies `ProviderExchange` and `model`/`effort`, but it cannot supply the `file` event contract, because that core change is absent from every ref checked above. That is why step 1 has to come first.

## Related, but not blocking

- `channels` `package.json` and the providers agent-runner manifest carry caret ranges while the skills' `nc:dep` policy requires exact pins.
- Refs #3095 (the maintenance-guide rewrite; it deliberately keeps drift state out of the doc and points here).

Assisted by Claude; reviewed and verified by a human before submission.
